import FooterComponent from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import React from "react";

type Props = {
   children: React.ReactNode;
   styles?: string | undefined;
};

const DefaultLayout = (props: Props) => {
   return (
      <>
         <Head>
            <title>Lofi Shop</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className="max-w-full">
            <Header />
            <section>{props.children}</section>
            <section>
               <FooterComponent />
            </section>
         </main>
      </>
   );
};

export default DefaultLayout;
