import Head from "next/head";
import React from "react";

type Props = {
   children: React.ReactNode;
   styles?: string;
};

const EmptyLayout = (props: Props) => {
   return (
      <div>
         <Head>
            <title>Lofi Shop</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className={props.styles}>{props.children}</main>
      </div>
   );
};

export default EmptyLayout;
