export type ProductType = {
    id: string,
    name: string,
    description: string,
    rating: number,
    origin: string,
    material: string,
    style: string,
    sample: string,
    price: number,
    subCategory: string,
    orders: number,
    photoUrl: string,
    size: string,
}
